---
- name: Hello World!
  hosts: all

  tasks:

  - name: Check the hostname and uptime 
    shell: hostname;update
    register: command_output

  - debug:
          var: command_output.stdout_lines
